spring.application.name=ShopSphere-Client

server.port=8080



# ===============================
# File Upload Size
# ===============================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
